const CARDS = [
{name:"Tronco",e:2,roles:["smallSpell"],targets:["swarm","bait"],vers:9},
{name:"Flechas",e:3,roles:["smallSpell","antiAir"],targets:["swarm","air"],vers:8},
{name:"Zap",e:2,roles:["smallSpell","reset"],targets:["swarm","inferno"],vers:8},
{name:"Bola de Fogo",e:4,roles:["bigSpell"],targets:["support","medium"],vers:9},
{name:"Veneno",e:4,roles:["bigSpell"],targets:["support","graveyard"],vers:9},
{name:"Relâmpago",e:6,roles:["bigSpell","reset"],targets:["support","building"],vers:7},
{name:"Valquíria",e:4,roles:["miniTank","splash","ground"],targets:["swarm","ground"],vers:9},
{name:"Cavaleiro",e:3,roles:["miniTank","ground"],targets:["ground"],vers:9},
{name:"Mini P.E.K.K.A",e:4,roles:["tankKiller","ground"],targets:["tank","hog"],vers:8},
{name:"P.E.K.K.A",e:7,roles:["tankKiller","tank","ground"],targets:["tank","bridge"],vers:7},
{name:"Caçador",e:4,roles:["antiAir","tankKiller","support"],targets:["air","tank","balloon"],vers:9},
{name:"Mosqueteira",e:4,roles:["antiAir","support"],targets:["air","support"],vers:9},
{name:"Arqueiras",e:3,roles:["antiAir","support"],targets:["air"],vers:8},
{name:"Mago Elétrico",e:4,roles:["antiAir","reset","support"],targets:["inferno","air"],vers:9},
{name:"Bebê Dragão",e:4,roles:["antiAir","splash","support"],targets:["swarm","air"],vers:9},
{name:"Executor",e:5,roles:["antiAir","splash","support"],targets:["swarm","air"],vers:7},
{name:"Bombardeiro",e:2,roles:["splash","ground"],targets:["swarm","ground"],vers:7},
{name:"Príncipe",e:5,roles:["ground","pressure"],targets:["medium","tank"],vers:7},
{name:"Príncipe das Trevas",e:4,roles:["splash","miniTank","pressure"],targets:["swarm","ground"],vers:8},
{name:"Fantasma Real",e:3,roles:["pressure","splash"],targets:["swarm","support"],vers:8},
{name:"Mega Servo",e:3,roles:["antiAir","support"],targets:["air","medium"],vers:8},
{name:"Servos",e:3,roles:["antiAir","swarm"],targets:["tank","air"],vers:7},
{name:"Horda de Servos",e:5,roles:["antiAir","swarm"],targets:["tank","air"],vers:5},
{name:"Gangue de Goblins",e:3,roles:["swarm","bait"],targets:["tank","ground"],vers:7},
{name:"Guardas",e:3,roles:["swarm","ground"],targets:["tank","ground"],vers:8},
{name:"Exército de Esqueletos",e:3,roles:["swarm"],targets:["tank","ground"],vers:6},
{name:"Espírito de Gelo",e:1,roles:["cycle"],targets:["swarm"],vers:7},
{name:"Esqueletos",e:1,roles:["cycle"],targets:["ground"],vers:7},
{name:"Torre Bomba",e:4,roles:["building","splash"],targets:["hog","ground"],vers:8},
{name:"Tesla",e:4,roles:["building","antiAir"],targets:["hog","air","tank"],vers:9},
{name:"Torre Inferno",e:5,roles:["building","tankKiller"],targets:["tank","giant","rg"],vers:8},
{name:"Canhão",e:3,roles:["building"],targets:["hog","ground"],vers:8},
{name:"Jaula de Goblin",e:4,roles:["building","miniTank"],targets:["hog","tank"],vers:9},
{name:"Corredor",e:4,roles:["wincon","hog"],targets:[],vers:8},
{name:"Balão",e:5,roles:["wincon","air","balloon"],targets:[],vers:7},
{name:"Cemitério",e:5,roles:["wincon","graveyard"],targets:[],vers:8},
{name:"Gigante Real",e:6,roles:["wincon","rg"],targets:[],vers:8},
{name:"Gigante",e:5,roles:["wincon","tank","giant"],targets:[],vers:7},
{name:"Golem",e:8,roles:["wincon","tank"],targets:[],vers:5},
{name:"Mineiro",e:3,roles:["wincon","miniTank"],targets:[],vers:9},
{name:"Barril de Goblins",e:3,roles:["wincon","bait"],targets:[],vers:7},
{name:"Ariete de Batalha",e:4,roles:["wincon","bridge"],targets:[],vers:7},
{name:"Porcos Reais",e:5,roles:["wincon","hog"],targets:[],vers:8},
{name:"Lava Hound",e:7,roles:["wincon","tank","air"],targets:[],vers:6},
{name:"Morteiro",e:4,roles:["wincon","building"],targets:[],vers:8},
{name:"X-Besta",e:6,roles:["wincon","building"],targets:[],vers:6},
{name:"Pescador",e:3,roles:["control","ground"],targets:["hog","tank"],vers:9},
{name:"Tornado",e:3,roles:["control","smallSpell"],targets:["hog","swarm"],vers:9},
{name:"Mago",e:5,roles:["antiAir","splash","support"],targets:["swarm","air"],vers:6},
{name:"Bruxa",e:5,roles:["support","swarm","antiAir"],targets:["ground"],vers:6},
{name:"Carrasco",e:5,roles:["antiAir","splash","support"],targets:["swarm","air"],vers:7},
{name:"Dragão Infernal",e:4,roles:["antiAir","tankKiller"],targets:["tank","air"],vers:8},
{name:"Morcegos",e:2,roles:["antiAir","swarm"],targets:["tank","air"],vers:7},
{name:"Máquina Voadora",e:4,roles:["antiAir","support"],targets:["air","support"],vers:7},
{name:"Arqueiro Mágico",e:4,roles:["antiAir","support","pressure"],targets:["swarm","support"],vers:8},
{name:"Lançador",e:5,roles:["splash","support"],targets:["ground","swarm"],vers:7},
{name:"Goblins",e:2,roles:["swarm","cycle"],targets:["ground"],vers:7},
{name:"Espírito Elétrico",e:1,roles:["cycle","reset"],targets:["swarm","inferno"],vers:8},
{name:"Barril de Bárbaro",e:2,roles:["smallSpell","ground"],targets:["swarm","bait"],vers:8},
{name:"Foguete",e:6,roles:["bigSpell"],targets:["support","building"],vers:6}
];
