'use strict';
// Original card artwork distributed by RoyaleAPI/cr-api-assets, stored locally.
const CARD_IMAGES={
 "Tronco": "the-log",
 "Flechas": "arrows",
 "Zap": "zap",
 "Bola de Fogo": "fireball",
 "Veneno": "poison",
 "Relâmpago": "lightning",
 "Valquíria": "valkyrie",
 "Cavaleiro": "knight",
 "Mini P.E.K.K.A": "mini-pekka",
 "P.E.K.K.A": "pekka",
 "Caçador": "hunter",
 "Mosqueteira": "musketeer",
 "Arqueiras": "archers",
 "Mago Elétrico": "electro-wizard",
 "Bebê Dragão": "baby-dragon",
 "Executor": "executioner",
 "Carrasco": "executioner",
 "Bombardeiro": "bomber",
 "Príncipe": "prince",
 "Príncipe das Trevas": "dark-prince",
 "Fantasma Real": "royal-ghost",
 "Mega Servo": "mega-minion",
 "Servos": "minions",
 "Horda de Servos": "minion-horde",
 "Gangue de Goblins": "goblin-gang",
 "Guardas": "guards",
 "Exército de Esqueletos": "skeleton-army",
 "Espírito de Gelo": "ice-spirit",
 "Esqueletos": "skeletons",
 "Torre Bomba": "bomb-tower",
 "Tesla": "tesla",
 "Torre Inferno": "inferno-tower",
 "Canhão": "cannon",
 "Jaula de Goblin": "goblin-cage",
 "Corredor": "hog-rider",
 "Balão": "balloon",
 "Cemitério": "graveyard",
 "Gigante Real": "royal-giant",
 "Gigante": "giant",
 "Golem": "golem",
 "Mineiro": "miner",
 "Barril de Goblins": "goblin-barrel",
 "Ariete de Batalha": "battle-ram",
 "Porcos Reais": "royal-hogs",
 "Lava Hound": "lava-hound",
 "Morteiro": "mortar",
 "X-Besta": "x-bow",
 "Pescador": "fisherman",
 "Tornado": "tornado",
 "Mago": "wizard",
 "Bruxa": "witch",
 "Dragão Infernal": "inferno-dragon",
 "Morcegos": "bats",
 "Máquina Voadora": "flying-machine",
 "Arqueiro Mágico": "magic-archer",
 "Lançador": "bowler",
 "Goblins": "goblins",
 "Espírito Elétrico": "electro-spirit",
 "Barril de Bárbaro": "barbarian-barrel",
 "Foguete": "rocket",
 "Bárbaros": "barbarians",
 "Goblins Lanceiros": "spear-goblins",
 "Esqueleto Gigante": "giant-skeleton",
 "Mago de Gelo": "ice-wizard",
 "Princesa": "princess",
 "Três Mosqueteiras": "three-musketeers",
 "Espírito de Fogo": "fire-spirit",
 "Sparky": "sparky",
 "Lenhador": "lumberjack",
 "Golem de Gelo": "ice-golem",
 "Goblin com Dardo": "dart-goblin",
 "Bárbaros de Elite": "elite-barbarians",
 "Bandida": "bandit",
 "Recrutas Reais": "royal-recruits",
 "Bruxa Sombria": "night-witch",
 "Domadora de Carneiro": "ram-rider",
 "Eletrocutadores": "zappies",
 "Patifes": "rascals",
 "Carrinho de Canhão": "cannon-cart",
 "Megacavaleiro": "mega-knight",
 "Barril de Esqueletos": "skeleton-barrel",
 "Destruidores de Muros": "wall-breakers",
 "Goblin Gigante": "goblin-giant",
 "Dragão Elétrico": "electro-dragon",
 "Pirotécnica": "firecracker",
 "Mineiro Bombado": "mighty-miner",
 "Golem de Elixir": "elixir-golem",
 "Curadora Guerreira": "battle-healer",
 "Rei Esqueleto": "skeleton-king",
 "Rainha Arqueira": "archer-queen",
 "Cavaleiro Dourado": "golden-knight",
 "Monge": "monk",
 "Dragões Esqueleto": "skeleton-dragons",
 "Bruxa Mãe": "mother-witch",
 "Gigante Elétrico": "electro-giant",
 "Fênix": "phoenix",
 "Cabana de Goblins": "goblin-hut",
 "Cabana de Bárbaros": "barbarian-hut",
 "Coletor de Elixir": "elixir-collector",
 "Lápide": "tombstone",
 "Fornalha": "furnace",
 "Escavadeira de Goblins": "goblin-drill",
 "Fúria": "rage",
 "Gelo": "freeze",
 "Terremoto": "earthquake",
 "Espírito Curador": "heal-spirit",
 "Bola de Neve": "giant-snowball",
 "Encomenda Real": "royal-delivery"
};
function cardImagePath(name){return `assets/cards/${CARD_IMAGES[name]}.png`;}
function cardArtwork(c,kind='pool-art'){return `<img class="${kind}" src="${cardImagePath(c.name)}" alt="" width="150" height="180" decoding="async" draggable="false">`;}
let artworkLoad=null;
function preloadArtwork(){
 if(typeof Image==='undefined')return Promise.resolve(0);
 if(artworkLoad)return artworkLoad;
 artworkLoad=new Promise(resolve=>{
  const slugs=[...new Set(Object.values(CARD_IMAGES))];let remaining=slugs.length,failed=0,done=false;
  const finish=()=>{if(done)return;done=true;clearTimeout(timeout);resolve(failed+remaining);};
  const timeout=setTimeout(finish,8000);
  for(const slug of slugs){const img=new Image();img.onload=()=>{remaining--;if(!remaining)finish();};img.onerror=()=>{failed++;remaining--;if(!remaining)finish();};img.src=`assets/cards/${slug}.png`;}
 });
 return artworkLoad;
}
